/* eslint-disable @next/next/no-img-element */
import React from 'react';
import classNames from 'classnames/bind';
import styles from './checkout.module.scss';
import Head from 'next/head';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faTrashCan } from '@fortawesome/free-solid-svg-icons';

const cx = classNames.bind(styles);

function Checkout() {
    return (
        <div className={cx('wrapper')}>
            <Head>
                <title>Checkout</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className={cx('grid', 'wide')}>
                <div className={cx('checkout__wrapper')}>
                    <div className={cx('row')}>
                        <div className={cx('checkout__infor')}>
                            <div className={cx('col', 'l-2')}>
                                <div className={cx('infor__img-wrapper')}>
                                    <img
                                        className={cx('infor__img')}
                                        src="https://www.horze.eu/dw/image/v2/AATB_PRD/on/demandware.static/-/Sites-hz-master-catalog/default/dwfdf7f6a8/large/26281_B.jpg?sw=1600&q=100&filename=blue-blue"
                                        alt="product-img"
                                    />
                                </div>
                            </div>
                            <div className={cx('col', 'l-4')}>
                                <div className={cx('infor__name-wrapper')}>
                                    <p className={cx('infor__name')}>NAME</p>
                                </div>
                            </div>
                            <div className={cx('col', 'l-4')}>
                                <div className={cx('infor__price-wrapper')}>
                                    <p className={cx('infor__price')}>PRICE</p>
                                </div>
                            </div>
                            <div className={cx('col', 'l-2')}>
                                <div className={cx('infor__delete-wrapper')}>
                                    <FontAwesomeIcon
                                        className={cx('infor__delete')}
                                        icon={faTrashCan}
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className={cx('row')}>
                        <div className={cx('checkout__btn-wrapper')}>
                            <button className={cx('checkout__btn')}>BUY</button>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
}

export default Checkout;
