/* eslint-disable @next/next/no-img-element */
import React, { useContext } from 'react';
import classNames from 'classnames/bind';
import styles from './checkout.module.scss';
import Head from 'next/head';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faTrashCan } from '@fortawesome/free-solid-svg-icons';
import { DataContext } from '../Context/DataContext';

const cx = classNames.bind(styles);

function Checkout() {
    const { items } = useContext(DataContext);

    return (
        <div className={cx('wrapper')}>
            <Head>
                <title>Checkout</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className={cx('grid', 'wide')}>
                <div className={cx('checkout__wrapper')}>
                    <div className={cx('row')}>
                        {items.length > 0 ? (
                            items.map((item) => (
                                <div
                                    key={item.id}
                                    className={cx('checkout__infor')}
                                >
                                    <div className={cx('col', 'l-2')}>
                                        <div
                                            className={cx('infor__img-wrapper')}
                                        >
                                            <img
                                                className={cx('infor__img')}
                                                src={item.image}
                                                alt="product-img"
                                            />
                                        </div>
                                    </div>
                                    <div className={cx('col', 'l-4')}>
                                        <div
                                            className={cx(
                                                'infor__name-wrapper'
                                            )}
                                        >
                                            <p className={cx('infor__name')}>
                                                {item.title}
                                            </p>
                                        </div>
                                    </div>
                                    <div className={cx('col', 'l-4')}>
                                        <div
                                            className={cx(
                                                'infor__price-wrapper'
                                            )}
                                        >
                                            <p className={cx('infor__price')}>
                                                {item.price} $
                                            </p>
                                        </div>
                                    </div>
                                    <div className={cx('col', 'l-2')}>
                                        <div
                                            className={cx(
                                                'infor__delete-wrapper'
                                            )}
                                        >
                                            <FontAwesomeIcon
                                                className={cx('infor__delete')}
                                                icon={faTrashCan}
                                            />
                                        </div>
                                    </div>
                                </div>
                            ))
                        ) : (
                            <div>No Product</div>
                        )}
                    </div>
                    <div className={cx('row')}>
                        <div className={cx('checkout__btn-wrapper')}>
                            <button className={cx('checkout__btn')}>BUY</button>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
}

export default Checkout;
