import Head from 'next/head';
// import useSWR from 'swr';
// import axios from 'axios';
import classNames from 'classnames/bind';
import styles from './home.module.scss';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { AdvertiseSlider } from '../components/AdvertiseSlider';
import { Program } from '../components/Program';
import { ProductCart } from '../components/ProductCart';

const cx = classNames.bind(styles);
// const fetcher = (url) => axios.get(url).then((res) => res.data);
// const { data, error } = useSWR(
//     'https://fakestoreapi.com/products',
//     fetcher
// );

export default function Home({ products }) {
    return (
        <div>
            <div className={cx('app_wrapper')}>
                <Head>
                    <title>E-Shop Next App</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className={cx('grid')}>
                    <div className={cx('row')}>
                        <Header />
                    </div>
                </div>
                <div className={cx('grid', 'wide')}>
                    <div className={cx('content')}>
                        <div className={cx('content__advertise')}>
                            <div className={cx('row', 'sm-gutter')}>
                                <div className={cx('l-8', 'm-12', 'c-12')}>
                                    <AdvertiseSlider />
                                </div>
                                <div className={cx('l-4', 'm-12', 'c-12')}>
                                    <Program />
                                </div>
                            </div>
                        </div>
                        <div className={cx('content__advertise')}>
                            <div className={cx('row', 'sm-gutter')}>
                                <div className={cx('l-7', 'm-12', 'c-12')}>
                                    <AdvertiseSlider />
                                </div>
                                <div className={cx('l-5', 'm-12', 'c-12')}>
                                    <Program />
                                </div>
                            </div>
                        </div>
                        <div className={cx('content__products')}>
                            <div className={cx('row', 'sm-gutter')}>
                                {products.map((prod) => (
                                    <div
                                        key={prod.id}
                                        className={cx('l-2', 'm-6', 'c-12')}
                                    >
                                        <ProductCart
                                            id={prod.id}
                                            name={prod.title}
                                            image={prod.image}
                                            price={prod.price}
                                        />
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
                <div className={cx('grid')}>
                    <div className={cx('row')}>
                        <Footer />
                    </div>
                </div>
            </div>
        </div>
    );
}

export async function getStaticProps() {
    const res = await fetch('https://fakestoreapi.com/products');
    const products = await res.json();

    return {
        props: {
            products,
        },
    };
}
